[package]
name = "sigma-ser"
version = "0.19.0"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
repository.workspace = true
edition.workspace = true
description = "Ergo binary serialization primitives"

[features]
default = ["std"]
std = ["core3/std"]

[dependencies]
thiserror = { workspace = true }
bitvec = { workspace = true }
bounded-vec = { workspace = true }
core3 = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
proptest-derive = { workspace = true }
derive_more = { workspace = true }
