[package]
name = "ergotree-interpreter"
version = "0.29.0"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
repository.workspace = true
edition.workspace = true
description = "ErgoTree interpreter"
exclude = ["proptest-regressions/*"]

[lib]
crate-type = ["rlib"]

[dependencies]
sigma-util = { workspace = true }
sigma-ser = { workspace = true }
ergo-chain-types = { workspace = true }
ergotree-ir = { workspace = true }
indexmap = { workspace = true }
k256 = { workspace = true }
elliptic-curve = { workspace = true }
blake2 = { workspace = true }
rand = { workspace = true, optional = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
derive_more = { workspace = true }
num-traits = { workspace = true }
base16 = { workspace = true }
proptest-derive = { workspace = true, optional = true }
bytes = { workspace = true }
num-bigint = { workspace = true }
bounded-vec = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
ergo_avltree_rust = { version = "0.1.1" }
gf2_192 = { version = "^0.29.0", path = "../gf2_192" }
miette = { workspace = true, optional = true }
hashbrown = { workspace = true }
core3 = { workspace = true }
sigma-test-util = { workspace = true, optional = true }

generic-array = "=0.14.7" #TODO: unpin this when k256 and elliptic-curve upgrade to generic-array 1.0 and remove the deprecation warnings

[features]
json = [
    "serde",
    "serde_json",
    "serde_with",
    "bounded-vec/serde",
    "ergotree-ir/json",
    "ergo-chain-types/json",
]
default = ["json", "std"]
std = ["rand", "miette", "ergotree-ir/std"]
arbitrary = [
    "std",
    "proptest",
    "proptest-derive",
    "ergotree-ir/arbitrary",
    "ergo-chain-types/arbitrary",
    "gf2_192/arbitrary",
    "sigma-test-util",
]

[dev-dependencies]
ergotree-ir = { workspace = true, features = ["arbitrary"] }
ergoscript-compiler = { workspace = true }
proptest = { workspace = true }
sigma-test-util = { workspace = true }
expect-test = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "eval_benches"
harness = false
required-features = ["arbitrary"]
