[package]
name = "ergo-rest"
version = "0.14.0"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
repository.workspace = true
edition.workspace = true
description = "Ergo node REST API library"
exclude = [
    "proptest-regressions/*"
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "^0.1"
bounded-integer = { workspace = true }
bounded-vec = { workspace = true, features=["serde"] }
ergo-chain-types = { workspace = true }
ergo-nipopow = { workspace = true }
ergotree-ir = { workspace =  true, features = ["json"] }
ergo-merkle-tree = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
derive_more = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
url = { workspace = true }
reqwest = { version = "0.12.24", default-features = false, features = ["json"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasmtimer = "=0.4.3"
wasm-bindgen-futures = "0.4"


[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.25"
features = [
    "console",
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "AbortController",
    "AbortSignal",
    "Response",
    "ReadableStream",
    "Window",
    "FormData",
    "Blob",
    "BlobPropertyBag",
    "ServiceWorkerGlobalScope",
    "RequestCredentials",
    "File",
    "Performance"
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true }
tokio-stream = { workspace = true }

[features]
json = ["serde_json"]
default = ["json"]

[dev-dependencies]
sigma-test-util = { workspace = true }
