name: JS tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  js_tests:
    name: run JS tests
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: bindings/ergo-lib-wasm
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get -y install nodejs

      - name: run tests
        run: |
          wasm-pack build
          npm install
          npm run test 
          
      - name: build alpha versions
        run: |
          npm run build-nodejs-alpha
          npm run build-browser-alpha

      - name: publish nodejs alpha version to npm
        if: ${{ secrets.NPM_TOKEN }} 
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./bindings/ergo-lib-wasm/pkg-nodejs/package.json
          tag: "alpha"

      - name: publish browser alpha version to npm
        if: ${{ secrets.NPM_TOKEN }} 
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./bindings/ergo-lib-wasm/pkg-browser/package.json
          tag: "alpha"
